import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { CreditCard, Check, Zap, Crown, ChevronRight, Receipt, Calendar } from "lucide-react";
import { motion } from "framer-motion";
import { Switch } from "@/components/ui/switch";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { SpotlightCard } from "@/components/ui/SpotlightCard";
import { JewelIcon } from "@/components/ui/JewelIcon";
import { useUserPlan } from "@/hooks/useUserPlan";
import { trackPlanUpgrade } from "@/lib/analytics";
import CreditPacks from "@/components/billing/CreditPacks";
import { openLemonSqueezyCheckout } from "@/lib/lemonSqueezy";
import { LEMON_SQUEEZY_PRICES } from "@/lib/lemonSqueezyPrices";

const Billing = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isLifetimeToggle, setIsLifetimeToggle] = useState(false);
  const { plan, isTrial, isStarter, isPro, isLifetime } = useUserPlan();

  useEffect(() => {
    const checkUser = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate("/auth");
        return;
      }

      const { data: { user } } = await supabase.auth.getUser();
      setUser(user);
      setLoading(false);
    };

    checkUser();
  }, [navigate]);

  const plans = [
    {
      name: "Free Trial",
      price: 0,
      period: "",
      icon: Zap,
      color: "gray",
      features: [
        "20 credits (one-time)",
        "1 credit = 1 email generated",
        "Basic email sequences",
        '"Generated by Mailgenpro" watermark',
        "Smart Preview"
      ]
    },
    {
      name: "Starter",
      price: isLifetimeToggle ? 59 : 19,
      period: isLifetimeToggle ? "one-time" : "month",
      icon: CreditCard,
      color: "blue",
      popular: true,
      showToggle: true,
      lifetimePrice: 59,
      features: [
        isLifetimeToggle ? "150 credits (never expires)" : "150 credits per month",
        "1 credit = 1 email generated",
        "Remove watermark",
        "Priority AI speed",
        "Email support"
      ]
    },
    {
      name: "Pro",
      price: 29,
      period: "month",
      icon: Crown,
      color: "purple",
      features: [
        "400 credits per month",
        "1 credit = 1 email generated",
        "Everything in Starter",
        "Auto-Translate",
        "Priority AI & early access"
      ]
    }
  ];

  const getCurrentPlanName = () => {
    if (isPro) return "Pro";
    if (isStarter) return "Starter";
    if (isLifetime) return "Starter (Lifetime)";
    return "Free Trial";
  };

  const handleCheckout = async (priceId: string, planName: string, price: number) => {
    if (!user?.id) {
      toast.error('Please log in to continue');
      return;
    }

    trackPlanUpgrade(planName, price);

    try {
      await openLemonSqueezyCheckout(priceId, user.id, user.email);
    } catch (error) {
      console.error('Checkout error:', error);
      toast.error('Failed to open checkout. Please try again.');
    }
  };

  const handleUpgrade = (planName: string) => {
    const priceConfig: { [key: string]: { priceId: string; price: number } } = {
      'Starter': {
        priceId: isLifetimeToggle ? LEMON_SQUEEZY_PRICES.STARTER_LIFETIME : LEMON_SQUEEZY_PRICES.STARTER_MONTHLY,
        price: isLifetimeToggle ? 59 : 19
      },
      'Pro': {
        priceId: LEMON_SQUEEZY_PRICES.PRO_MONTHLY,
        price: 29
      }
    };

    const config = priceConfig[planName];
    if (config) {
      handleCheckout(config.priceId, planName, config.price);
    }
  };

  const handleManageSubscription = async () => {
    try {
      const { data: usageData } = await supabase
        .from('user_usage')
        .select('lemonsqueezy_customer_id')
        .eq('user_id', user?.id)
        .maybeSingle();

      if ((usageData as any)?.lemonsqueezy_customer_id) {
        window.open(`https://app.lemonsqueezy.com/my-orders`, '_blank');
        toast.info('Manage your subscription in the Lemon Squeezy portal');
      } else {
        toast.error('No subscription found');
      }
    } catch (error) {
      toast.error('Failed to open subscription management');
    }
  };

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center min-h-[50vh]">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout
      headerTitle="Plans & Billing"
      headerDescription="Manage your subscription and payment methods"
    >
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-6xl mx-auto space-y-8"
      >
        {/* Current Plan Card */}
        <SpotlightCard className="p-8 border-primary/20">
          <div className="flex flex-col md:flex-row items-start justify-between gap-6">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <h2 className="text-2xl font-heading font-semibold">Current Plan</h2>
                <Badge variant="secondary" className="bg-primary/20 text-primary border-primary/20">
                  {getCurrentPlanName()}
                </Badge>
              </div>
              <p className="text-muted-foreground max-w-xl">
                {isTrial && "You're on the free trial. Upgrade to get more credits and unlock premium features."}
                {isStarter && "You're on the Starter plan. Upgrade to Pro for more credits and advanced features."}
                {isLifetime && "You have lifetime access to Starter features. Upgrade to Pro for even more."}
                {isPro && "You're on the Pro plan with full access to all features."}
              </p>
            </div>
            <div className="flex gap-3 w-full md:w-auto">
              {!isTrial && !isLifetime && (
                <Button variant="outline" onClick={handleManageSubscription} className="flex-1 md:flex-none border-white/10 hover:bg-white/5">
                  <CreditCard className="w-4 h-4 mr-2" />
                  Manage Subscription
                </Button>
              )}
              {!isPro && (
                <Button onClick={() => handleUpgrade(isStarter || isLifetime ? "Pro" : "Starter")} className="flex-1 md:flex-none btn-premium">
                  <Crown className="w-4 h-4 mr-2" />
                  Upgrade Now
                </Button>
              )}
            </div>
          </div>

          <div className="w-full h-px bg-white/5 my-8" />

          <div className="grid gap-4 md:grid-cols-3">
            <div className="p-5 rounded-xl bg-white/5 border border-white/5">
              <div className="flex items-center gap-2 mb-2">
                <div className="p-1.5 rounded-md bg-purple-500/20 text-purple-400">
                  <Receipt className="w-4 h-4" />
                </div>
                <p className="text-sm font-medium text-muted-foreground">Billing Cycle</p>
              </div>
              <p className="text-xl font-heading font-semibold ml-1">
                {isTrial ? "No Active Plan" : isLifetime ? "Lifetime" : "Monthly"}
              </p>
            </div>

            {!isTrial && !isLifetime && (
              <>
                <div className="p-5 rounded-xl bg-white/5 border border-white/5">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="p-1.5 rounded-md bg-blue-500/20 text-blue-400">
                      <Calendar className="w-4 h-4" />
                    </div>
                    <p className="text-sm font-medium text-muted-foreground">Renews On</p>
                  </div>
                  <p className="text-xl font-heading font-semibold ml-1">
                    {new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                  </p>
                </div>

                <div className="p-5 rounded-xl bg-white/5 border border-white/5">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="p-1.5 rounded-md bg-emerald-500/20 text-emerald-400">
                      <CreditCard className="w-4 h-4" />
                    </div>
                    <p className="text-sm font-medium text-muted-foreground">Payment Method</p>
                  </div>
                  <p className="text-xl font-heading font-semibold ml-1">•••• 4242</p>
                </div>
              </>
            )}
          </div>
        </SpotlightCard>

        {/* Available Plans */}
        <div>
          <h2 className="text-3xl font-heading font-bold mb-8">Available Plans</h2>
          <div className="grid gap-8 md:grid-cols-3">
            {plans.map((planItem, index) => {
              const isCurrentPlan = planItem.name.toLowerCase() === plan;
              const isPopular = planItem.popular;

              return (
                <motion.div
                  key={planItem.name}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <SpotlightCard
                    className={`p-8 relative h-full flex flex-col ${isPopular ? 'border-primary/50 shadow-2xl shadow-primary/10' : ''}`}
                    spotlightColor={isPopular ? "rgba(124, 58, 237, 0.2)" : undefined}
                  >
                    {isPopular && (
                      <div className="absolute top-0 right-0 bg-gradient-to-r from-violet-600 to-indigo-600 text-white text-[10px] font-bold tracking-widest px-3 py-1.5 rounded-bl-xl uppercase">
                        Most Popular
                      </div>
                    )}

                    <JewelIcon icon={planItem.icon} color={planItem.color as any} size="lg" className="mb-6" />

                    <h3 className="text-2xl font-bold mb-2">{planItem.name}</h3>

                    <div className="mb-8 min-h-[80px]">
                      <div className="flex items-baseline gap-1">
                        <span className="text-4xl font-bold tracking-tight">
                          ${planItem.showToggle && isLifetimeToggle && planItem.lifetimePrice ? planItem.lifetimePrice : planItem.price}
                        </span>
                        <span className="text-muted-foreground font-medium">
                          /{planItem.showToggle && isLifetimeToggle ? 'life' : planItem.period || 'forever'}
                        </span>
                      </div>

                      {planItem.showToggle && (
                        <div className="flex items-center gap-3 mt-4 p-1 bg-white/5 rounded-lg w-fit">
                          <Switch id="lifetime-mode" checked={isLifetimeToggle} onCheckedChange={setIsLifetimeToggle} className="scale-75 data-[state=checked]:bg-primary" />
                          <label htmlFor="lifetime-mode" className="text-xs font-medium cursor-pointer select-none pr-2">
                            {isLifetimeToggle ? "Lifetime Access" : "Monthly"}
                          </label>
                        </div>
                      )}
                    </div>

                    <Button
                      className={`w-full mb-8 py-6 rounded-xl text-base ${isPopular && !isCurrentPlan ? "btn-premium" : isCurrentPlan ? "border-white/10 hover:bg-white/5" : "bg-white/10 hover:bg-white/20"}`}
                      variant={isCurrentPlan ? "outline" : "default"}
                      disabled={isCurrentPlan || planItem.name === "Free Trial"}
                      onClick={() => {
                        if (planItem.name === "Free Trial") return;
                        handleUpgrade(planItem.name);
                      }}
                    >
                      {isCurrentPlan ? "Current Plan" : planItem.name === "Free Trial" ? "Included" : "Upgrade Plan"}
                      {!isCurrentPlan && planItem.name !== "Free Trial" && <ChevronRight className="w-4 h-4 ml-2" />}
                    </Button>

                    <div className="space-y-4 flex-1">
                      {planItem.features.map((feature) => (
                        <div key={feature} className="flex items-center gap-3">
                          <div className={`p-1 rounded-full ${isPopular ? "bg-primary/20 text-primary" : "bg-white/10 text-white"}`}>
                            <Check className="w-3 h-3" />
                          </div>
                          <span className="text-sm text-muted-foreground">{feature}</span>
                        </div>
                      ))}
                    </div>
                  </SpotlightCard>
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* Credit Packs Section */}
        {user && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="mt-12"
          >
            <CreditPacks userId={user.id} />
          </motion.div>
        )}
      </motion.div>
    </DashboardLayout>
  );
};

export default Billing;
