import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { CreditCard, Check, Zap, Crown, ChevronRight, Receipt, Calendar } from "lucide-react";
import { motion } from "framer-motion";
import { Switch } from "@/components/ui/switch";
import DashboardSidebar from "@/components/dashboard/DashboardSidebar";
import MobileSidebar from "@/components/dashboard/MobileSidebar";
import { useUserPlan } from "@/hooks/useUserPlan";
import { trackPlanUpgrade, trackButtonClick } from "@/lib/analytics";
import CreditPacks from "@/components/billing/CreditPacks";
import { openPaddleCheckout } from "@/lib/paddle";
import { PADDLE_PRICES } from "@/lib/paddlePrices";

const Billing = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isLifetimeToggle, setIsLifetimeToggle] = useState(false);
  const { plan, isTrial, isStarter, isPro, isLifetime } = useUserPlan();

  useEffect(() => {
    const checkUser = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate("/auth");
        return;
      }

      const { data: { user } } = await supabase.auth.getUser();
      setUser(user);
      setLoading(false);
    };

    checkUser();
  }, [navigate]);

  const plans = [
    {
      name: "Free Trial",
      price: 0,
      period: "",
      icon: Zap,
      color: "from-gray-500 to-gray-600",
      features: [
        "20 credits (one-time)",
        "1 credit = 1 email generated",
        "Basic email sequences",
        '"Generated by Mailgenpro" watermark',
        "Smart Preview"
      ]
    },
    {
      name: "Starter",
      price: isLifetimeToggle ? 59 : 19,
      period: isLifetimeToggle ? "one-time" : "month",
      icon: CreditCard,
      color: "from-primary to-accent",
      popular: true,
      showToggle: true,
      lifetimePrice: 59,
      features: [
        isLifetimeToggle ? "150 credits (never expires)" : "150 credits per month",
        "1 credit = 1 email generated",
        "Remove watermark",
        "Priority AI speed",
        "Email support"
      ]
    },
    {
      name: "Pro",
      price: 29,
      period: "month",
      icon: Crown,
      color: "from-accent to-primary",
      features: [
        "400 credits per month",
        "1 credit = 1 email generated",
        "Everything in Starter",
        "Auto-Translate",
        "Priority AI & early access"
      ]
    }
  ];

  const getCurrentPlanName = () => {
    if (isPro) return "Pro";
    if (isStarter) return "Starter";
    if (isLifetime) return "Starter (Lifetime)";
    return "Free Trial";
  };

  const handleCheckout = async (priceId: string, planName: string, price: number) => {
    if (!user?.id) {
      toast.error('Please log in to continue');
      return;
    }

    trackPlanUpgrade(planName, price);

    try {
      await openPaddleCheckout(priceId, user.id, user.email);
    } catch (error) {
      console.error('Checkout error:', error);
      toast.error('Failed to open checkout. Please try again.');
    }
  };

  const handleUpgrade = (planName: string) => {
    const priceConfig: { [key: string]: { priceId: string; price: number } } = {
      'Starter': {
        priceId: isLifetimeToggle ? PADDLE_PRICES.STARTER_LIFETIME : PADDLE_PRICES.STARTER_MONTHLY,
        price: isLifetimeToggle ? 59 : 11
      },
      'Pro': {
        priceId: PADDLE_PRICES.PRO_MONTHLY,
        price: 29
      }
    };

    const config = priceConfig[planName];
    if (config) {
      handleCheckout(config.priceId, planName, config.price);
    }
  };

  const handleManageSubscription = async () => {
    try {
      const { data: usageData } = await supabase
        .from('user_usage')
        .select('paddle_customer_id')
        .eq('user_id', user?.id)
        .maybeSingle(); // Use maybeSingle to avoid 406/error if record is missing

      if ((usageData as any)?.paddle_customer_id) {
        // Paddle customer portal - users can manage subscriptions at paddle.com
        window.open(`https://vendors.paddle.com/subscriptions/customers`, '_blank');
        toast.info('Manage your subscription in the Paddle portal');
      } else {
        toast.error('No subscription found');
      }
    } catch (error) {
      toast.error('Failed to open subscription management');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <div className="flex min-h-screen bg-background">
      <DashboardSidebar />

      <div className="flex-1 flex flex-col">
        {/* Top Bar */}
        <div className="sticky top-0 z-40 border-b border-border/40 glass-card">
          <div className="flex items-center justify-between px-6 py-4">
            <div className="flex items-center gap-4">
              <MobileSidebar />
              <div>
                <h1 className="text-3xl font-bold tracking-tight">Mailgenpro Plans</h1>
                <p className="text-sm text-muted-foreground">Manage your subscription and payment methods</p>
              </div>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="flex-1 overflow-y-auto p-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-6xl mx-auto space-y-8"
          >
            {/* Current Plan Card */}
            <Card className="glass-card p-6">
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-3 mb-2">
                    <h2 className="text-xl font-semibold">Current Plan</h2>
                    <Badge variant="secondary" className="bg-primary/10 text-primary">
                      {getCurrentPlanName()}
                    </Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    {isTrial && "You're on the free trial. Upgrade to get more credits and unlock premium features."}
                    {isStarter && "You're on the Starter plan. Upgrade to Pro for more credits and advanced features."}
                    {isLifetime && "You have lifetime access to Starter features. Upgrade to Pro for even more."}
                    {isPro && "You're on the Pro plan with full access to all features."}
                  </p>
                </div>
                <div className="flex gap-2">
                  {!isTrial && !isLifetime && (
                    <Button variant="outline" onClick={handleManageSubscription}>
                      <CreditCard className="w-4 h-4 mr-2" />
                      Manage Subscription
                    </Button>
                  )}
                  {!isPro && (
                    <Button onClick={() => handleUpgrade(isStarter || isLifetime ? "Pro" : "Starter")}>
                      <Crown className="w-4 h-4 mr-2" />
                      Upgrade Now
                    </Button>
                  )}
                </div>
              </div>

              <Separator className="my-6" />

              <div className="grid gap-4 md:grid-cols-3">
                <div className="p-4 rounded-lg bg-muted/30">
                  <div className="flex items-center gap-2 mb-2">
                    <Receipt className="w-4 h-4 text-muted-foreground" />
                    <p className="text-sm font-medium">Billing Cycle</p>
                  </div>
                  <p className="text-lg font-semibold">
                    {isTrial ? "No active subscription" : isLifetime ? "Lifetime" : "Monthly"}
                  </p>
                </div>

                {!isTrial && !isLifetime && (
                  <>
                    <div className="p-4 rounded-lg bg-muted/30">
                      <div className="flex items-center gap-2 mb-2">
                        <Calendar className="w-4 h-4 text-muted-foreground" />
                        <p className="text-sm font-medium">Next Billing Date</p>
                      </div>
                      <p className="text-lg font-semibold">
                        {new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                      </p>
                    </div>

                    <div className="p-4 rounded-lg bg-muted/30">
                      <div className="flex items-center gap-2 mb-2">
                        <CreditCard className="w-4 h-4 text-muted-foreground" />
                        <p className="text-sm font-medium">Payment Method</p>
                      </div>
                      <p className="text-lg font-semibold">On file</p>
                    </div>
                  </>
                )}
              </div>
            </Card>

            {/* Available Plans */}
            <div>
              <h2 className="text-2xl font-bold mb-6">Available Plans</h2>
              <div className="grid gap-6 md:grid-cols-3">
                {plans.map((planItem, index) => {
                  const Icon = planItem.icon;
                  const isCurrentPlan = planItem.name.toLowerCase() === plan;

                  return (
                    <motion.div
                      key={planItem.name}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.1 }}
                    >
                      <Card className={`glass-card p-6 relative overflow-hidden ${planItem.popular ? 'border-primary/50 shadow-lg shadow-primary/10' : ''}`}>
                        {planItem.popular && (
                          <div className="absolute top-0 right-0 bg-gradient-to-r from-violet-600 to-indigo-600 text-white text-xs font-medium px-3 py-1 rounded-bl-lg">
                            POPULAR
                          </div>
                        )}

                        <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${planItem.color} flex items-center justify-center mb-4`}>
                          <Icon className="w-6 h-6 text-white" />
                        </div>

                        <h3 className="text-2xl font-bold mb-2">{planItem.name}</h3>

                        <div className="mb-6">
                          <span className="text-4xl font-bold">
                            ${planItem.showToggle && isLifetimeToggle && planItem.lifetimePrice ? planItem.lifetimePrice : planItem.price}
                          </span>
                          <span className="text-muted-foreground">
                            /{planItem.showToggle && isLifetimeToggle ? 'one-time' : planItem.period}
                          </span>
                        </div>

                        {planItem.showToggle && (
                          <div className="flex items-center gap-3 p-3 rounded-xl bg-secondary/50 mb-6">
                            <span className={!isLifetimeToggle ? 'font-medium text-sm' : 'text-muted-foreground text-sm'}>Monthly</span>
                            <Switch checked={isLifetimeToggle} onCheckedChange={setIsLifetimeToggle} />
                            <span className={isLifetimeToggle ? 'font-medium text-sm' : 'text-muted-foreground text-sm'}>Lifetime</span>
                          </div>
                        )}

                        <Button
                          className={`w-full mb-6 ${!isCurrentPlan && planItem.name !== "Free Trial" ? "btn-premium" : ""}`}
                          variant={isCurrentPlan ? "outline" : "default"}
                          disabled={isCurrentPlan || planItem.name === "Free Trial"}
                          onClick={() => {
                            if (planItem.name === "Free Trial") return;
                            handleUpgrade(planItem.name);
                          }}
                        >
                          {isCurrentPlan ? "Current Plan" : planItem.name === "Free Trial" ? "Current Plan" : "Upgrade"}
                          {!isCurrentPlan && planItem.name !== "Free Trial" && <ChevronRight className="w-4 h-4 ml-2" />}
                        </Button>

                        <Separator className="mb-4" />

                        <ul className="space-y-3">
                          {planItem.features.map((feature) => (
                            <li key={feature} className="flex items-start gap-2">
                              <Check className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                              <span className="text-sm">{feature}</span>
                            </li>
                          ))}
                        </ul>
                      </Card>
                    </motion.div>
                  );
                })}
              </div>
            </div>

            {/* Billing History */}
            <Card className="glass-card p-6">
              <h2 className="text-xl font-semibold mb-4">Billing History</h2>
              <p className="text-sm text-muted-foreground">
                Your payment history and invoices will appear here once you upgrade to a paid plan.
              </p>
            </Card>

            {/* Credit Packs Section */}
            {user && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="mt-8"
              >
                <CreditPacks userId={user.id} />
              </motion.div>
            )}
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default Billing;
